Book.create(isbn: '0385539436', title: 'Rogue Lawyer', author_id:2 , genre: 'Fiction', abstract: "Sebastian Rudd is not your typical street lawyer. He works out of a customized bulletproof van, complete with Wi-Fi, a bar, a small fridge, fine leather chairs, a hidden gun compartment, and a heavily armed driver. He has no firm, no partners, no associates, and only one employee, his driver, who’s also his bodyguard, law clerk, confidant, and golf caddy. He lives alone in a small but extremely safe penthouse apartment, and his primary piece of furniture is a vintage pool table. He drinks small-batch bourbon and carries a gun.",
 pages: 354, image_cover_url: 'http://ecx.images-amazon.com/images/I/51At4zgdkYL._SX327_BO1,204,203,200_.jpg', published_on: 'October 20, 2015' , total_in_library: 5)

 Book.create(isbn: '1627792414', title: 'Killing Reagan, The Violent Assault That Changed a Presidency', author_id:3 , genre: 'Non-Fiction', abstract: "From the bestselling team of Bill O'Reilly and Martin Dugard comes Killing Reagan, a page-turning epic account of the career of President Ronald Reagan that tells the vivid story of his rise to power -- and the forces of evil that conspired to bring him down.",
 pages: 320, image_cover_url: 'http://ecx.images-amazon.com/images/I/51DBSqi5jBL._SX329_BO1,204,203,200_.jpg', published_on: 'September 22, 2015' , total_in_library: 5)

 Book.create(isbn: '1627792415', title: 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', author_id:4 , genre: 'Non-Fiction', abstract: "For readers of Unbroken, out of the depths of the Depression comes an irresistible story about beating the odds and finding hope in the most desperate of times—the improbable, intimate account of how nine working-class boys from the American West showed the world at the 1936 Olympics in Berlin what true grit really meant.",
 pages: 417, image_cover_url: 'http://ecx.images-amazon.com/images/I/51x7paY8iYL._SX324_BO1,204,203,200_.jpg', published_on: 'June 4, 2013' , total_in_library: 5)

Book.create(isbn: '1627792416', title: 'The Martian', author_id:5 , genre: 'Fiction', abstract: "Remember Man Plus, Frederik Pohl’s award-winning 1976 novel about a cyborg astronaut who’s sent, alone, to Mars? Imagine, instead, that the astronaut was just a regular guy, part of a team sent to the red planet, and that, through a series of tragic events, he’s left behind, stranded and facing certain death. That’s the premise of this gripping and (given its subject matter) startlingly plausible novel. The story is told mostly through the log entries of astronaut Mark Watney, chronicling his efforts to survive: making the prefab habitat livable and finding a way to grow food, make water, and get himself off the planet. Interspersed among the log entries are sections told from the point of view of the NASA specialists, back on Earth, who discover that Watney is not dead (as everyone assumed) and scramble together a rescue plan. There are some inevitable similarities between the book and the 1964 movie Robinson Crusoe on Mars, but where the movie was a broad sci-fi adventure, the novel is a tightly constructed and completely believable story of a man’s ingenuity and strength in the face of seemingly insurmountable odds. Riveting. --David Pitt", pages: 385, image_cover_url: 'http://ecx.images-amazon.com/images/I/51v1t48NzmL._SX322_BO1,204,203,200_.jpg', published_on: 'June 4, 2013' , total_in_library: 5)

Book.create(isbn: '1627792417', title: 'Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History', author_id: 6, genre: 'Non-Fiction', abstract: "Brian Kilmeade and his co-author Don Yaeger return with another fascinating historical narrative. Like their bestseller George Washington's Secret Six, Thomas Jefferson and the Tripoli Pirates sheds light on a vitally important episode forgotten by most Americans. Only weeks after President Jefferson's 1801 inauguration, he decided to confront the Tripoli pirates who had been kidnapping American ships and sailors, among other outrageous acts. Though inclined toward diplomacy, Jefferson sent warships to blockade Tripoli and protect American shipping, and then escalated to all-out war against the Barbary states.", pages: 249, image_cover_url: 'http://ecx.images-amazon.com/images/I/51PPkeSJP5L._SX329_BO1,204,203,200_.jpg', published_on: 'November 3, 2015' , total_in_library: 5)

Author.create(name: 'Magda Szabo' , dob: 'October 5, 1917', nationality: 'Hungarian', awards: 'Baumgarten Prize', biography: 'Magda Szabó was a major Hungarian novelist. She also wrote dramas, essays, studies, memories and poetry. Born in Debrecen, Szabó graduated at the University of Debrecen as a teacher of Latin and of Hungarian' , image_url: 'http://rha.chookdigital.net/authors/szabo,%20magda.jpg')


Author.create(name: 'John Grisham' , dob: 'February 8, 1955', nationality: 'American', awards: 'Harper Lee Prize', biography: "Long before his name became synonymous with the modern legal thriller, John Grisham was working 60-70 hours a week at a small Southaven, Mississippi law practice, squeezing in time before going to the office and during courtroom recesses to work on his hobby--writing his first novel. Born on February 8, 1955 in Jonesboro, Arkansas, to a construction worker and a homemaker, John Grisham as a child dreamed of being a professional baseball player. Realizing he didn't have the right stuff for a pro career, he shifted gears and majored in accounting at Mississippi State University. After graduating from law school at Ole Miss in 1981, he went on to practice law for nearly a decade in Southaven, specializing in criminal defense and personal injury litigation. One day at the DeSoto County courthouse, Grisham overheard the harrowing testimony of a twelve-year-old rape victim and was inspired to start a novel exploring what would have happened if the girl's father had murdered her assailants.", image_url: 'https://images-na.ssl-images-amazon.com/images/I/411bLjUOvdL._UX250_.jpg')

Author.create(name: "Bill O'Reilly" , dob: 'September 10, 1949', nationality: 'American', awards: 'The New York Times Best Sellers List', biography: "Bill O'Reilly is proud to report that The Factor remains the most watched show on cable news, just as it has for 15 years. Every night more than 5-million viewers tune in to The Factor. It's a remarkable fact, and that support and loyalty also account, in no small measure, for the success of Bill's many other projects." , image_url: 'https://images-na.ssl-images-amazon.com/images/I/415A8DT0tJL._UX250_.jpg')

Author.create(name: 'Daniel James Brown' , dob: 'October 1, 1951', nationality: 'American', awards: '2014 Washington State Book Award for Nonfiction', biography: 'Daniel James Brown grew up in the San Francisco Bay Area and attended Diablo Valley College, the University of California at Berkeley, and UCLA. He taught writing at San Jose State University and Stanford before becoming a technical writer and editor. He now writes narrative nonfiction books full time. His primary interest as a writer is in bringing compelling historical events to life vividly and accurately.' , image_url: 'https://images-na.ssl-images-amazon.com/images/I/71FYibtCO-L._UX250_.jpg')

Author.create(name: 'Andy Weir' , dob: 'June 16, 1972', nationality: 'American', awards: 'Goodreads Choice Awards Best Science Fiction', biography: 'ANDY WEIR was first hired as a programmer for a national laboratory at age fifteen and has been working as a software engineer ever since. He is also a lifelong space nerd and a devoted hobbyist of subjects like relativistic physics, orbital mechanics, and the history of manned spaceflight. The Martian is his first novel.' , image_url: 'https://images-na.ssl-images-amazon.com/images/I/71FYibtCO-L._UX250_.jpg')

Author.create(name: 'Brian Kilmeade' , dob: 'June 16, 1972', nationality: 'American', awards: 'Goodreads Choice Awards Best Science Fiction', biography: 'BRIAN KILMEADE and DON YAEGER are the coauthors of George Washington’s Secret Six, a New York Times bestseller for more than five months. Kilmeade cohosts Fox News Channel’s morning show Fox & Friends and hosts the daily national radio show Kilmeade & Friends. He lives on Long Island. This is his fourth book. Yaeger has written or cowritten twenty-four books and lives in Florida.' , image_url: 'https://images-na.ssl-images-amazon.com/images/I/4105EzZM3aL._UX250_.jpg')